# 04 — Optuna Tuning

ini ganti Grid Search dengan **Tree-structured Parzen Estimator (Optuna)** untuk mengeksplorasi ruang parameter yang lebih luas dengan jumlah trial lebih sedikit.

- `learning_rate` (log-uniform 1e-4 .. 1e-1)
- `optimizer ∈ {adam, rmsprop}`
- `lstm_units ∈ {16, 32, 64, 128}`
- `dropout_rate ∈ [0, 0.4]` step 0.05

Output: best params per stasiun + perbandingan terhadap Grid Search dari notebook 03.

In [1]:
import sys, pathlib
sys.path.insert(0, str(pathlib.Path.cwd().parent))

import pandas as pd

from src import config as C
from src.data_loader import load_all_stations
from src.evaluation import compute_metrics
from src.preprocessing import build_pipeline, inverse_target
from src.tuning_optuna import run_optuna, fit_best

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
FEATURES = C.WEATHER_COLS + [C.AOD_COL, C.TARGET]
STATIONS_TO_RUN = C.HEALTHY_STATIONS
N_TRIALS = 30
EPOCHS = 100
PATIENCE = 15

dfs = load_all_stations(reindex=True)

In [3]:
rows = []
for s in STATIONS_TO_RUN:
    print(f'\n=== {s} ===')
    data = build_pipeline(dfs[s], FEATURES, smooth_aod=False)

    study = run_optuna(data, n_trials=N_TRIALS, epochs=EPOCHS, patience=PATIENCE)
    model, history = fit_best(study, data, epochs=EPOCHS, patience=PATIENCE)

    n_features = data['X_train'].shape[2]
    y_pred = model.predict(data['X_test'], verbose=0).flatten()
    y_pred = inverse_target(y_pred, data['scaler'], data['target_idx'], n_features)
    y_true = inverse_target(data['y_test'], data['scaler'], data['target_idx'], n_features)
    m = compute_metrics(y_true, y_pred)

    rows.append({'station': s, **study.best_params, **m})
    model.save(C.MODEL_DIR / f'04_optuna_{s}.keras')
    print(f'   best R²={m["R2"]:.4f} | {study.best_params}')

df_optuna = pd.DataFrame(rows)
df_optuna.to_csv(C.METRICS_DIR / '04_optuna_summary.csv', index=False)
df_optuna

[I 2026-04-27 13:10:42,095] A new study created in memory with name: no-name-5fa33f73-6a21-4060-9303-081bbdc61411

=== us_embassy_1 ===
WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

[I 2026-04-27 13:16:44,121] Trial 0 finished with value: 0.442237515910923 and parameters: {'learning_rate': 0.0005611516415334506, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.35000000000000003}. Best is trial 0 with value: 0.442237515910923.
[I 2026-04-27 13:20:25,419] Trial 1 finished with value: 0.4968690978894894 and parameters: {'learning_rate': 0.0015930522616241021, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.4968690978894894.

WARNING:tensorflow:5 out of the last 11 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000020B6CA2CFE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000020B6CA2CFE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

[I 2026-04-27 13:23:42,524] Trial 2 finished with value: 0.4715158120042381 and parameters: {'learning_rate': 0.0004059611610484307, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.4968690978894894.
[I 2026-04-27 13:26:38,345] Trial 3 finished with value: 0.3283549292467367 and parameters: {'learning_rate': 0.000816845589476017, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.4968690978894894.
[I 2026-04-27 13:27:47,685] Trial 4 finished with value: 0.011337041027407402 and parameters: {'learning_rate': 0.00013492834268013249, 'optimizer': 'rmsprop', 'lstm_units': 16, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.4968690978894894.
[I 2026-04-27 13:28:57,404] Trial 5 finished with value: 0.05110082628556023 and parameters: {'learning_rate': 0.00017541893487450815, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.2}. Best is trial 1 with value: 0.4968690978894894.
[I 2026-04-27 13:32:31,668] Trial 6 finished with value: 0.2537406853236407 and parameters: {'learning_rate': 0.0012399967836846098, 'optimizer': 'rmsprop', 'lstm_units': 32, 'dropout_rate': 0.4}. Best is trial 1 with value: 0.4968690978894894.
[I 2026-04-27 13:37:05,363] Trial 7 finished with value: 0.4806356946869994 and parameters: {'learning_rate': 0.00015030900645056822, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.4968690978894894.
[I 2026-04-27 13:40:43,257] Trial 8 finished with value: 0.5128060714525174 and parameters: {'learning_rate': 0.0003646439558980723, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 8 with value: 0.5128060714525174.
[I 2026-04-27 13:42:27,665] Trial 9 finished with value: 0.1461410069596446 and parameters: {'learning_rate': 0.00010257563974185662, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.05}. Best is trial 8 with value: 0.5128060714525174.
[I 2026-04-27 13:45:15,900] Trial 10 finished with value: 0.43806654095512443 and parameters: {'learning_rate': 0.007767353816237056, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 8 with value: 0.5128060714525174.
[I 2026-04-27 13:48:15,609] Trial 11 finished with value: 0.4539628041910697 and parameters: {'learning_rate': 0.002127662272356018, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 8 with value: 0.5128060714525174.
[I 2026-04-27 13:49:29,651] Trial 12 finished with value: 0.0035471328841669703 and parameters: {'learning_rate': 0.0030854733446305095, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 8 with value: 0.5128060714525174.
[I 2026-04-27 13:51:21,906] Trial 13 finished with value: 0.3627316290954834 and parameters: {'learning_rate': 0.00032740079365842635, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.30000000000000004}. Best is trial 8 with value: 0.5128060714525174.
[I 2026-04-27 13:53:15,823] Trial 14 finished with value: 0.3544768878743415 and parameters: {'learning_rate': 0.0016382061352101032, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.25}. Best is trial 8 with value: 0.5128060714525174.
[I 2026-04-27 13:54:13,425] Trial 15 finished with value: -0.0002791637001418046 and parameters: {'learning_rate': 0.004258459397995672, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 8 with value: 0.5128060714525174.
[I 2026-04-27 13:57:39,456] Trial 16 finished with value: 0.4734096780412903 and parameters: {'learning_rate': 0.000842387815265513, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 8 with value: 0.5128060714525174.
[I 2026-04-27 14:02:20,054] Trial 17 finished with value: 0.5547937712782345 and parameters: {'learning_rate': 0.0003074326026550764, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 14:06:15,840] Trial 18 finished with value: 0.1972890949560906 and parameters: {'learning_rate': 0.0002814145272515245, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 14:11:51,974] Trial 19 finished with value: 0.5151450731704648 and parameters: {'learning_rate': 0.00020716040560935504, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 14:17:36,186] Trial 20 finished with value: 0.4761125530412841 and parameters: {'learning_rate': 0.00024250447500682456, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.2}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 14:22:06,153] Trial 21 finished with value: 0.4762845706126022 and parameters: {'learning_rate': 0.0005600685136984707, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 14:27:15,266] Trial 22 finished with value: 0.4989957324713451 and parameters: {'learning_rate': 0.00020928119675494756, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 14:35:14,313] Trial 23 finished with value: 0.4573573023728844 and parameters: {'learning_rate': 0.0004592715939397241, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 14:40:04,934] Trial 24 finished with value: 0.3746166562884644 and parameters: {'learning_rate': 0.000322594333477254, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 14:46:33,991] Trial 25 finished with value: 0.4854495385369003 and parameters: {'learning_rate': 0.00010063522997390904, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 14:53:16,721] Trial 26 finished with value: 0.3591447975896932 and parameters: {'learning_rate': 0.0006030374670905297, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.15000000000000002}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 15:00:45,998] Trial 27 finished with value: 0.5122530340486835 and parameters: {'learning_rate': 0.00021715347124113055, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 15:07:18,046] Trial 28 finished with value: 0.49130689574070663 and parameters: {'learning_rate': 0.0003866077596728798, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 15:11:22,318] Trial 29 finished with value: 0.38735600255035096 and parameters: {'learning_rate': 0.0006230959645429313, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.0}. Best is trial 17 with value: 0.5547937712782345.
[I 2026-04-27 15:20:09,831] A new study created in memory with name: no-name-99adc7e9-fcaa-475f-8b55-99f1b494675e

   best R²=-3743226.9185 | {'learning_rate': 0.0003074326026550764, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}

=== us_embassy_2 ===

[I 2026-04-27 15:23:31,960] Trial 0 finished with value: -0.397548168298022 and parameters: {'learning_rate': 0.0005611516415334506, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.35000000000000003}. Best is trial 0 with value: -0.397548168298022.
[I 2026-04-27 15:27:06,627] Trial 1 finished with value: 0.30006074296959173 and parameters: {'learning_rate': 0.0015930522616241021, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.30006074296959173.
[I 2026-04-27 15:32:22,554] Trial 2 finished with value: 0.34474270403062923 and parameters: {'learning_rate': 0.0004059611610484307, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.15000000000000002}. Best is trial 2 with value: 0.34474270403062923.
[I 2026-04-27 15:38:05,612] Trial 3 finished with value: 0.44528582060624056 and parameters: {'learning_rate': 0.000816845589476017, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 15:39:18,802] Trial 4 finished with value: -0.1445053942404153 and parameters: {'learning_rate': 0.00013492834268013249, 'optimizer': 'rmsprop', 'lstm_units': 16, 'dropout_rate': 0.15000000000000002}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 15:40:38,070] Trial 5 finished with value: 0.17054338571693461 and parameters: {'learning_rate': 0.00017541893487450815, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.2}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 15:45:18,885] Trial 6 finished with value: 0.23861542451379625 and parameters: {'learning_rate': 0.0012399967836846098, 'optimizer': 'rmsprop', 'lstm_units': 32, 'dropout_rate': 0.4}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 15:53:16,807] Trial 7 finished with value: 0.42776068762143893 and parameters: {'learning_rate': 0.00015030900645056822, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.15000000000000002}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 15:58:26,736] Trial 8 finished with value: 0.3802933811657295 and parameters: {'learning_rate': 0.0003646439558980723, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 16:04:07,511] Trial 9 finished with value: 0.33043299734582354 and parameters: {'learning_rate': 0.00010257563974185662, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.05}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 16:06:31,224] Trial 10 finished with value: 0.21133604932276295 and parameters: {'learning_rate': 0.006987046490086249, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 16:13:08,529] Trial 11 finished with value: 0.35123854296245494 and parameters: {'learning_rate': 0.002724152422851781, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 16:14:45,938] Trial 12 finished with value: -0.013786980083326128 and parameters: {'learning_rate': 0.003691979171780842, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.15000000000000002}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 16:17:41,296] Trial 13 finished with value: 0.3336076122357553 and parameters: {'learning_rate': 0.00025583411781984023, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 3 with value: 0.44528582060624056.
[I 2026-04-27 16:21:30,127] Trial 14 finished with value: 0.4463734395776725 and parameters: {'learning_rate': 0.0007148659495423891, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:22:00,612] Trial 15 finished with value: -0.13894758853735167 and parameters: {'learning_rate': 0.0007403661818984221, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:22:45,125] Trial 16 finished with value: 0.014722911565011598 and parameters: {'learning_rate': 0.001800055478731078, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:23:29,423] Trial 17 finished with value: -0.0013521509642360208 and parameters: {'learning_rate': 0.0008222579722650779, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:27:44,553] Trial 18 finished with value: 0.435773583547883 and parameters: {'learning_rate': 0.0005554835386525194, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:28:52,322] Trial 19 finished with value: 0.10908262312695671 and parameters: {'learning_rate': 0.0028818386329330214, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:29:37,571] Trial 20 finished with value: -0.4043415511611348 and parameters: {'learning_rate': 0.009429671505981832, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:30:23,592] Trial 21 finished with value: -0.16915020756406296 and parameters: {'learning_rate': 0.0005234690942549068, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:31:09,288] Trial 22 finished with value: -0.08185904133465693 and parameters: {'learning_rate': 0.001047158080315055, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:35:22,397] Trial 23 finished with value: 0.39492508409345595 and parameters: {'learning_rate': 0.00028576229243484647, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:36:13,845] Trial 24 finished with value: 0.04329196748675945 and parameters: {'learning_rate': 0.000684850848103145, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.2}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:36:55,787] Trial 25 finished with value: 0.027127052905091542 and parameters: {'learning_rate': 0.0012090050836214014, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 14 with value: 0.4463734395776725.
[I 2026-04-27 16:40:45,735] Trial 26 finished with value: 0.4689486291505658 and parameters: {'learning_rate': 0.0004465965132556476, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 26 with value: 0.4689486291505658.
[I 2026-04-27 16:44:03,398] Trial 27 finished with value: 0.4208291312329474 and parameters: {'learning_rate': 0.0002195910361110156, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 26 with value: 0.4689486291505658.
[I 2026-04-27 16:47:22,921] Trial 28 finished with value: 0.2318080379164209 and parameters: {'learning_rate': 0.0003866077596728798, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.30000000000000004}. Best is trial 26 with value: 0.4689486291505658.
[I 2026-04-27 17:43:08,729] Trial 29 finished with value: 0.289288655682307 and parameters: {'learning_rate': 0.0017795853276700445, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.15000000000000002}. Best is trial 26 with value: 0.4689486291505658.
[I 2026-04-27 17:44:32,589] A new study created in memory with name: no-name-10419c90-eeac-406b-81e4-b4270c29c6cd

   best R²=-0.0016 | {'learning_rate': 0.0004465965132556476, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}

=== bundaran_hi ===

[I 2026-04-27 17:47:00,090] Trial 0 finished with value: 0.31085624535923473 and parameters: {'learning_rate': 0.0005611516415334506, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.35000000000000003}. Best is trial 0 with value: 0.31085624535923473.
[I 2026-04-27 17:49:56,780] Trial 1 finished with value: 0.49255366009221035 and parameters: {'learning_rate': 0.0015930522616241021, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.49255366009221035.
[I 2026-04-27 17:54:39,482] Trial 2 finished with value: 0.36203529536075385 and parameters: {'learning_rate': 0.0004059611610484307, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.49255366009221035.
[I 2026-04-27 18:01:21,124] Trial 3 finished with value: 0.5705096929676228 and parameters: {'learning_rate': 0.000816845589476017, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:02:39,847] Trial 4 finished with value: 0.10258885142609875 and parameters: {'learning_rate': 0.00013492834268013249, 'optimizer': 'rmsprop', 'lstm_units': 16, 'dropout_rate': 0.15000000000000002}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:04:42,943] Trial 5 finished with value: 0.027907912087075215 and parameters: {'learning_rate': 0.00017541893487450815, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.2}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:06:56,282] Trial 6 finished with value: -0.05521624990753482 and parameters: {'learning_rate': 0.0012399967836846098, 'optimizer': 'rmsprop', 'lstm_units': 32, 'dropout_rate': 0.4}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:11:19,813] Trial 7 finished with value: 0.42512654561937047 and parameters: {'learning_rate': 0.00015030900645056822, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.15000000000000002}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:15:01,076] Trial 8 finished with value: 0.46521384041021496 and parameters: {'learning_rate': 0.0003646439558980723, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:16:34,977] Trial 9 finished with value: 0.16017346831721235 and parameters: {'learning_rate': 0.00010257563974185662, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.05}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:17:54,992] Trial 10 finished with value: -0.5292067995076424 and parameters: {'learning_rate': 0.006987046490086249, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:19:54,762] Trial 11 finished with value: 0.013981935388824862 and parameters: {'learning_rate': 0.0020124870829750963, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:24:38,815] Trial 12 finished with value: 0.5306910834110182 and parameters: {'learning_rate': 0.0030854733446305095, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:26:18,460] Trial 13 finished with value: 0.001319359606318793 and parameters: {'learning_rate': 0.003949511766981021, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.30000000000000004}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:28:35,083] Trial 14 finished with value: 0.2142191232998688 and parameters: {'learning_rate': 0.0032138964777636233, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:36:01,272] Trial 15 finished with value: 0.5637821842152069 and parameters: {'learning_rate': 0.0007240215559387987, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:42:02,225] Trial 16 finished with value: 0.5241864712607648 and parameters: {'learning_rate': 0.0009505731048930307, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:48:06,540] Trial 17 finished with value: 0.5556501389228503 and parameters: {'learning_rate': 0.0007397296381783295, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 18:55:59,048] Trial 18 finished with value: 0.2407770366661881 and parameters: {'learning_rate': 0.0002766682207572691, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:03:31,104] Trial 19 finished with value: 0.5373859780675372 and parameters: {'learning_rate': 0.0006688947418945576, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.30000000000000004}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:07:44,091] Trial 20 finished with value: 0.4605608407749757 and parameters: {'learning_rate': 0.0002548756620290486, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.2}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:13:13,237] Trial 21 finished with value: 0.526381979568346 and parameters: {'learning_rate': 0.0008235098206863926, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:16:26,728] Trial 22 finished with value: 0.5687359442058927 and parameters: {'learning_rate': 0.000525826551126831, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.30000000000000004}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:20:20,117] Trial 23 finished with value: 0.5343298699478549 and parameters: {'learning_rate': 0.0005308357531753822, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.35000000000000003}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:24:15,622] Trial 24 finished with value: 0.5276952392998316 and parameters: {'learning_rate': 0.0011600483131933253, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.30000000000000004}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:25:15,622] Trial 25 finished with value: 0.0015160345066451697 and parameters: {'learning_rate': 0.0018104662653391835, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.35000000000000003}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:28:51,541] Trial 26 finished with value: 0.36771841748327194 and parameters: {'learning_rate': 0.00043861301505250397, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.2}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:30:59,611] Trial 27 finished with value: 0.37358175642617975 and parameters: {'learning_rate': 0.0002195910361110156, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.4}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:33:00,107] Trial 28 finished with value: 0.43396030176421607 and parameters: {'learning_rate': 0.00032670588841034664, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.30000000000000004}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:35:19,268] Trial 29 finished with value: 0.36541267555057033 and parameters: {'learning_rate': 0.0005747398178521822, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.35000000000000003}. Best is trial 3 with value: 0.5705096929676228.
[I 2026-04-27 19:38:21,067] A new study created in memory with name: no-name-ee0a21fc-7937-4699-9223-e6dad8426f98

   best R²=0.6413 | {'learning_rate': 0.000816845589476017, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}

=== kelapa_gading ===

[I 2026-04-27 19:39:45,327] Trial 0 finished with value: 0.2991198224031747 and parameters: {'learning_rate': 0.0005611516415334506, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.35000000000000003}. Best is trial 0 with value: 0.2991198224031747.
[I 2026-04-27 19:41:50,130] Trial 1 finished with value: 0.5333593303592762 and parameters: {'learning_rate': 0.0015930522616241021, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.5333593303592762.
[I 2026-04-27 19:44:21,883] Trial 2 finished with value: 0.47146867231130773 and parameters: {'learning_rate': 0.0004059611610484307, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.5333593303592762.
[I 2026-04-27 19:47:16,499] Trial 3 finished with value: 0.4619204452268859 and parameters: {'learning_rate': 0.000816845589476017, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.5333593303592762.
[I 2026-04-27 19:47:43,752] Trial 4 finished with value: -0.28479447727334994 and parameters: {'learning_rate': 0.00013492834268013249, 'optimizer': 'rmsprop', 'lstm_units': 16, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.5333593303592762.
[I 2026-04-27 19:49:00,700] Trial 5 finished with value: 0.3083893966258078 and parameters: {'learning_rate': 0.00017541893487450815, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.2}. Best is trial 1 with value: 0.5333593303592762.
[I 2026-04-27 19:51:47,275] Trial 6 finished with value: 0.46833342566755976 and parameters: {'learning_rate': 0.0012399967836846098, 'optimizer': 'rmsprop', 'lstm_units': 32, 'dropout_rate': 0.4}. Best is trial 1 with value: 0.5333593303592762.
[I 2026-04-27 19:55:04,586] Trial 7 finished with value: 0.4742560076925839 and parameters: {'learning_rate': 0.00015030900645056822, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.5333593303592762.
[I 2026-04-27 19:58:10,755] Trial 8 finished with value: 0.5408026264522473 and parameters: {'learning_rate': 0.0003646439558980723, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:00:08,934] Trial 9 finished with value: 0.43130801028746213 and parameters: {'learning_rate': 0.00010257563974185662, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.05}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:01:02,140] Trial 10 finished with value: 0.2404714279580379 and parameters: {'learning_rate': 0.007767353816237056, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:03:06,055] Trial 11 finished with value: 0.37383258213027337 and parameters: {'learning_rate': 0.002127662272356018, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:05:23,504] Trial 12 finished with value: 0.42240426909496964 and parameters: {'learning_rate': 0.0030854733446305095, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:07:48,043] Trial 13 finished with value: 0.40909930946721573 and parameters: {'learning_rate': 0.00032740079365842635, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.30000000000000004}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:09:44,003] Trial 14 finished with value: 0.32430099439948123 and parameters: {'learning_rate': 0.0016382061352101032, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.25}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:11:22,839] Trial 15 finished with value: 0.34454587972951567 and parameters: {'learning_rate': 0.004258459397995672, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:13:12,015] Trial 16 finished with value: 0.4683059361954801 and parameters: {'learning_rate': 0.000842387815265513, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:16:59,079] Trial 17 finished with value: 0.48167728010038346 and parameters: {'learning_rate': 0.0003074326026550764, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:19:47,414] Trial 18 finished with value: 0.4316122109919571 and parameters: {'learning_rate': 0.0006886443335114074, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:20:39,864] Trial 19 finished with value: -0.024789676569186403 and parameters: {'learning_rate': 0.00022664494065941692, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.2}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:21:43,608] Trial 20 finished with value: -9.93968085616359e-09 and parameters: {'learning_rate': 0.008182815063812085, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:23:41,428] Trial 21 finished with value: 0.3884205166301695 and parameters: {'learning_rate': 0.0003157197735741055, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:26:39,879] Trial 22 finished with value: 0.5085721483665011 and parameters: {'learning_rate': 0.0005055653893030875, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:29:00,446] Trial 23 finished with value: 0.4332159899422593 and parameters: {'learning_rate': 0.001320904973813319, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 8 with value: 0.5408026264522473.
[I 2026-04-27 20:33:47,706] Trial 24 finished with value: 0.5546329000782296 and parameters: {'learning_rate': 0.00042116165756953775, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 24 with value: 0.5546329000782296.
[I 2026-04-27 20:35:58,746] Trial 25 finished with value: 0.3331783388207501 and parameters: {'learning_rate': 0.0027528955191994343, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 24 with value: 0.5546329000782296.
[I 2026-04-27 20:36:31,360] Trial 26 finished with value: -0.28824789350282254 and parameters: {'learning_rate': 0.00023345604730318345, 'optimizer': 'rmsprop', 'lstm_units': 16, 'dropout_rate': 0.15000000000000002}. Best is trial 24 with value: 0.5546329000782296.
[I 2026-04-27 20:39:00,724] Trial 27 finished with value: 0.3884670239060174 and parameters: {'learning_rate': 0.0010986050866314168, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.25}. Best is trial 24 with value: 0.5546329000782296.
[I 2026-04-27 20:41:47,951] Trial 28 finished with value: 0.5081752268535957 and parameters: {'learning_rate': 0.0005290201000968307, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 24 with value: 0.5546329000782296.
[I 2026-04-27 20:44:16,444] Trial 29 finished with value: 0.48945396797894725 and parameters: {'learning_rate': 0.0006760430745064562, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 24 with value: 0.5546329000782296.
[I 2026-04-27 20:52:26,951] A new study created in memory with name: no-name-80df0c18-32df-4287-812f-879b8293dacb

   best R²=0.6460 | {'learning_rate': 0.00042116165756953775, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}

=== jagakarsa ===

[I 2026-04-27 20:54:43,610] Trial 0 finished with value: 0.08304846843938363 and parameters: {'learning_rate': 0.0005611516415334506, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.35000000000000003}. Best is trial 0 with value: 0.08304846843938363.
[I 2026-04-27 20:58:31,221] Trial 1 finished with value: 0.3089969064637421 and parameters: {'learning_rate': 0.0015930522616241021, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.3089969064637421.
[I 2026-04-27 21:01:13,244] Trial 2 finished with value: 0.15448191692648172 and parameters: {'learning_rate': 0.0004059611610484307, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.3089969064637421.
[I 2026-04-27 21:05:47,987] Trial 3 finished with value: 0.41017473075537847 and parameters: {'learning_rate': 0.000816845589476017, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:08:03,748] Trial 4 finished with value: -0.2738132364631285 and parameters: {'learning_rate': 0.00013492834268013249, 'optimizer': 'rmsprop', 'lstm_units': 16, 'dropout_rate': 0.15000000000000002}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:12:40,525] Trial 5 finished with value: 0.17573295925069343 and parameters: {'learning_rate': 0.00017541893487450815, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.2}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:15:46,054] Trial 6 finished with value: 0.1752518546660401 and parameters: {'learning_rate': 0.0012399967836846098, 'optimizer': 'rmsprop', 'lstm_units': 32, 'dropout_rate': 0.4}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:20:09,011] Trial 7 finished with value: 0.12385842570527728 and parameters: {'learning_rate': 0.00015030900645056822, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.15000000000000002}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:21:53,353] Trial 8 finished with value: 0.03141598767088305 and parameters: {'learning_rate': 0.0003646439558980723, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:26:14,100] Trial 9 finished with value: 0.17269827466009346 and parameters: {'learning_rate': 0.00010257563974185662, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.05}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:27:47,783] Trial 10 finished with value: -0.005672373109782303 and parameters: {'learning_rate': 0.006987046490086249, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:31:59,466] Trial 11 finished with value: 0.3991418251450649 and parameters: {'learning_rate': 0.0020124870829750963, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:35:23,100] Trial 12 finished with value: 0.4012455015180417 and parameters: {'learning_rate': 0.0030854733446305095, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:38:41,049] Trial 13 finished with value: 2.540584151400349e-05 and parameters: {'learning_rate': 0.003949511766981021, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.30000000000000004}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:42:32,879] Trial 14 finished with value: 0.27968295940584886 and parameters: {'learning_rate': 0.0032138964777636233, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:48:45,401] Trial 15 finished with value: 0.34947615493888984 and parameters: {'learning_rate': 0.0007240215559387987, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.25}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:51:13,005] Trial 16 finished with value: -0.00020676800009278296 and parameters: {'learning_rate': 0.009011286786227042, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 21:55:23,929] Trial 17 finished with value: 0.37031686265926567 and parameters: {'learning_rate': 0.004884311700953688, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 22:00:05,456] Trial 18 finished with value: 0.3690385603436954 and parameters: {'learning_rate': 0.002191656727911478, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 22:05:32,052] Trial 19 finished with value: 0.3974140648679211 and parameters: {'learning_rate': 0.0007863608368091759, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.2}. Best is trial 3 with value: 0.41017473075537847.
[I 2026-04-27 22:09:07,841] Trial 20 finished with value: 0.41912097326918996 and parameters: {'learning_rate': 0.00111283191738115, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:12:26,429] Trial 21 finished with value: 0.41806019844663467 and parameters: {'learning_rate': 0.0012217944016579589, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:16:38,151] Trial 22 finished with value: 0.40752376246920774 and parameters: {'learning_rate': 0.001047158080315055, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:18:41,387] Trial 23 finished with value: 0.0026257694942453114 and parameters: {'learning_rate': 0.000373285923337048, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:22:54,060] Trial 24 finished with value: 0.3998012927905864 and parameters: {'learning_rate': 0.0015109187726026936, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:28:13,095] Trial 25 finished with value: 0.3847017538779196 and parameters: {'learning_rate': 0.0005563642788923009, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:33:34,578] Trial 26 finished with value: 0.3118446187102434 and parameters: {'learning_rate': 0.000748153438276082, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:36:48,623] Trial 27 finished with value: 0.08090889442069416 and parameters: {'learning_rate': 0.0002195910361110156, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:42:19,745] Trial 28 finished with value: 0.412689561856717 and parameters: {'learning_rate': 0.001020534807840094, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.1}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:44:41,467] Trial 29 finished with value: 0.005270460136309607 and parameters: {'learning_rate': 0.002229684586547168, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.15000000000000002}. Best is trial 20 with value: 0.41912097326918996.
[I 2026-04-27 22:48:26,861] A new study created in memory with name: no-name-8380fb94-6fc9-4e00-8fb2-3fa7d0411ac7

   best R²=0.5259 | {'learning_rate': 0.00111283191738115, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}

=== lubang_buaya ===

[I 2026-04-27 22:50:04,400] Trial 0 finished with value: 0.18597198712211027 and parameters: {'learning_rate': 0.0005611516415334506, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.35000000000000003}. Best is trial 0 with value: 0.18597198712211027.
[I 2026-04-27 22:51:38,235] Trial 1 finished with value: 0.4440480961682547 and parameters: {'learning_rate': 0.0015930522616241021, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 22:53:24,779] Trial 2 finished with value: 0.31866622334980366 and parameters: {'learning_rate': 0.0004059611610484307, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 22:55:26,198] Trial 3 finished with value: 0.4207243632023583 and parameters: {'learning_rate': 0.000816845589476017, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 22:56:15,749] Trial 4 finished with value: 0.17282532561110175 and parameters: {'learning_rate': 0.00013492834268013249, 'optimizer': 'rmsprop', 'lstm_units': 16, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 22:57:24,812] Trial 5 finished with value: 0.245064161822503 and parameters: {'learning_rate': 0.00017541893487450815, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.2}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 22:58:37,977] Trial 6 finished with value: 0.2930882873532267 and parameters: {'learning_rate': 0.0012399967836846098, 'optimizer': 'rmsprop', 'lstm_units': 32, 'dropout_rate': 0.4}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 22:59:53,689] Trial 7 finished with value: 0.28955209431467366 and parameters: {'learning_rate': 0.00015030900645056822, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:01:47,836] Trial 8 finished with value: 0.3402249929066714 and parameters: {'learning_rate': 0.0003646439558980723, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:03:52,524] Trial 9 finished with value: 0.2314517402572922 and parameters: {'learning_rate': 0.00010257563974185662, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:05:52,719] Trial 10 finished with value: 0.357160614885367 and parameters: {'learning_rate': 0.00603888958059908, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:08:33,003] Trial 11 finished with value: 0.3801200166517077 and parameters: {'learning_rate': 0.0020124870829750963, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:09:33,829] Trial 12 finished with value: -0.000499586988655043 and parameters: {'learning_rate': 0.0030854733446305095, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:11:45,998] Trial 13 finished with value: 0.3989137573998164 and parameters: {'learning_rate': 0.0010199795772106827, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.30000000000000004}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:15:15,088] Trial 14 finished with value: 0.3286447148060325 and parameters: {'learning_rate': 0.0026477692329090253, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:16:09,506] Trial 15 finished with value: -0.008753013752384353 and parameters: {'learning_rate': 0.006880486866269893, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:17:23,168] Trial 16 finished with value: 0.38721073921990745 and parameters: {'learning_rate': 0.0014378657994477838, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.1}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:19:18,897] Trial 17 finished with value: 0.4210447757030361 and parameters: {'learning_rate': 0.0006212430243154707, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:20:16,095] Trial 18 finished with value: 0.2322050005618469 and parameters: {'learning_rate': 0.0002814145272515245, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:21:10,604] Trial 19 finished with value: 0.0012651344279045462 and parameters: {'learning_rate': 0.004179548824576805, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:22:49,467] Trial 20 finished with value: 0.30341307512916293 and parameters: {'learning_rate': 0.0006711632979128916, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.2}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:25:01,259] Trial 21 finished with value: 0.4026830942918308 and parameters: {'learning_rate': 0.0006990551259891295, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:26:53,764] Trial 22 finished with value: 0.4031417899538261 and parameters: {'learning_rate': 0.0018281475050971282, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:28:37,900] Trial 23 finished with value: 0.4186260917146921 and parameters: {'learning_rate': 0.0008270341238805857, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:30:18,574] Trial 24 finished with value: 0.35311455174549766 and parameters: {'learning_rate': 0.0005058742332462175, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:31:53,034] Trial 25 finished with value: 0.43656253958161306 and parameters: {'learning_rate': 0.0009778908899086428, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:32:52,014] Trial 26 finished with value: 0.26298322911213845 and parameters: {'learning_rate': 0.0012718200216079298, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:34:32,189] Trial 27 finished with value: 0.34704808511614804 and parameters: {'learning_rate': 0.00026779835805829317, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:36:29,183] Trial 28 finished with value: 0.40102696678964433 and parameters: {'learning_rate': 0.0019173171079424243, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:37:24,931] Trial 29 finished with value: -0.003659286407431628 and parameters: {'learning_rate': 0.004346450644988553, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.30000000000000004}. Best is trial 1 with value: 0.4440480961682547.
[I 2026-04-27 23:38:57,565] A new study created in memory with name: no-name-034edb97-be6b-4f17-bfcd-2520dcbcde10

   best R²=-0.0536 | {'learning_rate': 0.0015930522616241021, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}

=== kebun_jeruk ===

[I 2026-04-27 23:40:01,332] Trial 0 finished with value: 0.039525022923620035 and parameters: {'learning_rate': 0.0005611516415334506, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.35000000000000003}. Best is trial 0 with value: 0.039525022923620035.
[I 2026-04-27 23:41:49,346] Trial 1 finished with value: 0.5540952740380163 and parameters: {'learning_rate': 0.0015930522616241021, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:43:47,446] Trial 2 finished with value: 0.43060066132097885 and parameters: {'learning_rate': 0.0004059611610484307, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:45:33,094] Trial 3 finished with value: 0.5470499259887422 and parameters: {'learning_rate': 0.000816845589476017, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:46:34,625] Trial 4 finished with value: -0.32783497487219404 and parameters: {'learning_rate': 0.00013492834268013249, 'optimizer': 'rmsprop', 'lstm_units': 16, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:47:21,341] Trial 5 finished with value: -0.02574990845036207 and parameters: {'learning_rate': 0.00017541893487450815, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.2}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:47:59,506] Trial 6 finished with value: 0.15939129661950802 and parameters: {'learning_rate': 0.0012399967836846098, 'optimizer': 'rmsprop', 'lstm_units': 32, 'dropout_rate': 0.4}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:51:53,095] Trial 7 finished with value: 0.4771840479425611 and parameters: {'learning_rate': 0.00015030900645056822, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.15000000000000002}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:53:48,852] Trial 8 finished with value: 0.49085305282293346 and parameters: {'learning_rate': 0.0003646439558980723, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:56:33,986] Trial 9 finished with value: 0.3125012393623059 and parameters: {'learning_rate': 0.00010257563974185662, 'optimizer': 'adam', 'lstm_units': 32, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:57:46,517] Trial 10 finished with value: 0.38047484651472907 and parameters: {'learning_rate': 0.00603888958059908, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-27 23:59:05,483] Trial 11 finished with value: 0.4714384145950792 and parameters: {'learning_rate': 0.0020124870829750963, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:01:30,066] Trial 12 finished with value: 0.4842312463385722 and parameters: {'learning_rate': 0.0030854733446305095, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:02:53,399] Trial 13 finished with value: 0.4148070521825732 and parameters: {'learning_rate': 0.0010199795772106827, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.30000000000000004}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:04:28,642] Trial 14 finished with value: 0.3702368530679381 and parameters: {'learning_rate': 0.0026477692329090253, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.25}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:05:18,306] Trial 15 finished with value: -0.24642993891075382 and parameters: {'learning_rate': 0.006880486866269893, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:07:12,402] Trial 16 finished with value: 0.529234032967957 and parameters: {'learning_rate': 0.0014378657994477838, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.1}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:09:06,715] Trial 17 finished with value: 0.536431045816223 and parameters: {'learning_rate': 0.0006212430243154707, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:10:19,557] Trial 18 finished with value: 0.4404717118509238 and parameters: {'learning_rate': 0.0042615485251909216, 'optimizer': 'rmsprop', 'lstm_units': 128, 'dropout_rate': 0.1}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:11:15,969] Trial 19 finished with value: 0.18830508926353362 and parameters: {'learning_rate': 0.000740928480172689, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.2}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:13:51,476] Trial 20 finished with value: 0.5163921530053622 and parameters: {'learning_rate': 0.00027764911832674005, 'optimizer': 'adam', 'lstm_units': 128, 'dropout_rate': 0.05}. Best is trial 1 with value: 0.5540952740380163.
[I 2026-04-28 00:16:33,493] Trial 21 finished with value: 0.5558388521965639 and parameters: {'learning_rate': 0.0006990551259891295, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 21 with value: 0.5558388521965639.
[I 2026-04-28 00:18:17,284] Trial 22 finished with value: 0.538972747322189 and parameters: {'learning_rate': 0.0018281475050971282, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 21 with value: 0.5558388521965639.
[I 2026-04-28 00:21:01,080] Trial 23 finished with value: 0.553232651109819 and parameters: {'learning_rate': 0.0009242528590941297, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 21 with value: 0.5558388521965639.
[I 2026-04-28 00:23:43,999] Trial 24 finished with value: 0.5420265475176052 and parameters: {'learning_rate': 0.0014481217110215584, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 21 with value: 0.5558388521965639.
[I 2026-04-28 00:25:57,190] Trial 25 finished with value: 0.5359177401756774 and parameters: {'learning_rate': 0.00047562811391669007, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}. Best is trial 21 with value: 0.5558388521965639.
[I 2026-04-28 00:29:30,811] Trial 26 finished with value: 0.499990449568107 and parameters: {'learning_rate': 0.0009791266666805021, 'optimizer': 'rmsprop', 'lstm_units': 64, 'dropout_rate': 0.15000000000000002}. Best is trial 21 with value: 0.5558388521965639.
[I 2026-04-28 00:33:50,479] Trial 27 finished with value: 0.4977591140193801 and parameters: {'learning_rate': 0.00025500416076821984, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.1}. Best is trial 21 with value: 0.5558388521965639.
[I 2026-04-28 00:35:39,322] Trial 28 finished with value: 0.4739674515956719 and parameters: {'learning_rate': 0.002498643456884566, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.05}. Best is trial 21 with value: 0.5558388521965639.
[I 2026-04-28 00:36:36,354] Trial 29 finished with value: 0.4863326626884976 and parameters: {'learning_rate': 0.004346450644988553, 'optimizer': 'adam', 'lstm_units': 16, 'dropout_rate': 0.0}. Best is trial 21 with value: 0.5558388521965639.

   best R²=0.5202 | {'learning_rate': 0.0006990551259891295, 'optimizer': 'adam', 'lstm_units': 64, 'dropout_rate': 0.0}

,station,learning_rate,optimizer,lstm_units,dropout_rate,R2,MSE,RMSE,MAE
0,us_embassy_1,0.000307,adam,128,0.00,-3.743227e+06,1.664473e+09,40797.947769,19618.684208
1,us_embassy_2,0.000447,rmsprop,128,0.10,-1.621711e-03,6.437204e+02,25.371646,21.658303
2,bundaran_hi,0.000817,adam,128,0.05,6.413085e-01,3.234068e+02,17.983516,13.357601
3,kelapa_gading,0.000421,adam,128,0.05,6.460235e-01,1.875588e+02,13.695210,10.674044
4,jagakarsa,0.001113,adam,128,0.00,5.259171e-01,1.608693e+02,12.683427,8.429898
5,lubang_buaya,0.001593,adam,16,0.05,-5.356521e-02,6.385809e+02,25.270158,20.310780
6,kebun_jeruk,0.000699,adam,64,0.00,5.202040e-01,4.567227e+02,21.371072,17.561974

## Perbandingan Grid Search vs Optuna

In [4]:
df_grid = pd.read_csv(C.METRICS_DIR / '03_grid_best_summary.csv')[['station', 'R2']].rename(columns={'R2': 'R2_grid'})
df_opt  = df_optuna[['station', 'R2']].rename(columns={'R2': 'R2_optuna'})
comp = df_grid.merge(df_opt, on='station')
comp['delta'] = comp['R2_optuna'] - comp['R2_grid']
comp.to_csv(C.METRICS_DIR / '04_grid_vs_optuna.csv', index=False)
comp

         station   R2_grid     R2_optuna         delta
0  kelapa_gading  0.634426  6.460235e-01  1.159701e-02
1    bundaran_hi  0.596756  6.413085e-01  4.455226e-02
2    kebun_jeruk  0.591850  5.202040e-01 -7.164647e-02
3      jagakarsa  0.488738  5.259171e-01  3.717865e-02
4   us_embassy_2  0.415823 -1.621711e-03 -4.174443e-01
5   lubang_buaya  0.017091 -5.356521e-02 -7.065654e-02
6   us_embassy_1 -0.217306 -3.743227e+06 -3.743227e+06